services:
  tickets_api:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - path: .env
        required: false
    environment:
           DATABASE_URL: ${DATABASE_URL}

volumes:
  postgres_data:
